# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [1]:
# No code solution (reading)

⚠️ **ATTENTION! The answers differ from those presented in the original repository. This is due to the fact that the current notebook uses a newer version of PyTorch.**

In [2]:
# Import torch
import torch

torch.__version__

'2.2.1+cu121'

### 2. Create a random tensor with shape `(7, 7)`.


In [3]:
# Create random tensor
tensor_1 = torch.rand((7, 7))
print(tensor_1, tensor_1.shape)

tensor([[0.6937, 0.0613, 0.8638, 0.3246, 0.6798, 0.9275, 0.7122],
        [0.3544, 0.8911, 0.8211, 0.8923, 0.3189, 0.1316, 0.7654],
        [0.1233, 0.7408, 0.7906, 0.8252, 0.9843, 0.9108, 0.9371],
        [0.9208, 0.6555, 0.3290, 0.7242, 0.7316, 0.3871, 0.5985],
        [0.4167, 0.9322, 0.3823, 0.5426, 0.0491, 0.2963, 0.2774],
        [0.5905, 0.1632, 0.0808, 0.3421, 0.5604, 0.2534, 0.8816],
        [0.5977, 0.7011, 0.0140, 0.8087, 0.6956, 0.9058, 0.2754]]) torch.Size([7, 7])


### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [4]:
# Create another random tensor
tensor_2 = torch.rand((1, 7))
print(tensor_2, tensor_2.shape)

# Perform matrix multiplication
tensor_2 = tensor_2.t()
res = torch.mm(tensor_1, tensor_2)
print(res, res.shape)

tensor([[0.3701, 0.4699, 0.2996, 0.0935, 0.0812, 0.1682, 0.4015]]) torch.Size([1, 7])
tensor([[1.0718],
        [1.2347],
        [1.3171],
        [1.1798],
        [0.9227],
        [0.7934],
        [0.9498]]) torch.Size([7, 1])


### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [5]:
# Set manual seed
torch.manual_seed(0)

# Create two random tensors
tensor_1 = torch.rand((7, 7))
tensor_2 = torch.rand((1, 7))

# Matrix multiply tensors
res_0 = torch.mm(tensor_1, tensor_2.T)
print(res_0, res_0.size())

tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]]) torch.Size([7, 1])


### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [6]:
# Set random seed on the GPU
torch.cuda.manual_seed(1234)


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [7]:
# Set random seed
torch.manual_seed(1234)

# Check for access to GPU
# Create two random tensors on GPU

if torch.cuda.is_available():
    device = torch.device('cuda')

    # Создадим тензоры на GPU
    tensor_3 = torch.rand((2, 3), device=device)
    tensor_4 = torch.rand((2, 3), device=device)
    print('Device:', device)
    print(tensor_3)
    print(tensor_4)
else:
    print('GPU is not available.')

Device: cuda
tensor([[0.1272, 0.8167, 0.5440],
        [0.6601, 0.2721, 0.9737]], device='cuda:0')
tensor([[0.6208, 0.0276, 0.3255],
        [0.1114, 0.6812, 0.3608]], device='cuda:0')



### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [8]:
# Perform matmul on tensor_A and tensor_B
res_7 = torch.matmul(tensor_3, tensor_4.T)
print(res_7, res_7.shape)

tensor([[0.2786, 0.7668],
        [0.7343, 0.6102]], device='cuda:0') torch.Size([2, 2])


### 8. Find the maximum and minimum values of the output of 7.

In [9]:
# Find max
max_val = torch.max(res_7)
print('Max value:', max_val)

# Find min
min_val = torch.min(res_7)
print('Min value:', min_val)

Max value: tensor(0.7668, device='cuda:0')
Min value: tensor(0.2786, device='cuda:0')


### 9. Find the maximum and minimum index values of the output of 7.

In [10]:
# Find arg max
max_ind= torch.argmax(res_7)
print('Max index:', max_ind)

# Find arg min
min_ind = torch.argmin(res_7)
print('Min index:', min_ind)

Max index: tensor(1, device='cuda:0')
Min index: tensor(0, device='cuda:0')



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [11]:
# Set seed
torch.manual_seed(7)

# Create random tensor
tensor_5 = torch.rand((1, 1, 1, 10))
print(tensor_5, tensor_5.shape)

# Remove single dimensions
tensor_sq = tensor_5.squeeze()

# Print out tensors and their shapes
print(tensor_sq, tensor_sq.shape)

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
